# Supplier.create!([
#   {name: "Carrot Top", email: "info@carrottop.com", phone: "312-266-3991"},
#   {name: "Love All Day", email: "info@loveallday.com", phone: "312-666-3992"},
#   {name: "Forced Exposure", email: "info@forcedexposure.com", phone: "773-616-3902"},
#   {name: "Matador", email: "info@matador.com", phone: "701-600-9992"},
#   {name: "MG Art", email: "info@manuelgottsching.com", phone: "702-808-112"}
# ])
# Vinyl.create!([
#   {artist_name: "Ryley Walker", record_title: "Golden Sings That Have Been Sung", genre: "Improv/Jazz Indie Folk", description: "Chicago's Ryley Walker continues his journey with the fantastic \"Golden Sings That Have Been Sung.\" Walker leads some of the finest players in the improv/ jazz scene with his effortless sounding guitar playing & almost-spoken, stream of consciousness singing style. This limited expanded edition features a 41 minute version of the song \"Sullen Mind\" recorded live for SiriusXM.", playtime: 48, label: "Dead Oceans", price: 19, supplier_id: 1},
#   {artist_name: "Celestino", record_title: "Protector's Tea", genre: "Zen Tea Ambient", description: "Featuring beautifully mastered sound by Jae-Soo Yi of Riverman Music in Seoul, in an edition of 300 copies housed in a sturdy, archival old-style LP jacket.", playtime: 30, label: "Love All Day", price: 19, supplier_id: 1},
#   {artist_name: "Sabbatical", record_title: "Sundown", genre: "Ambient", description: "Sundown is an album 6 years in the making by the Chicago ambient/drone artist Pete Prezzano aka SABBATICAL. These beautiful drone pieces are well recorded & the tones are warmly represented on vinyl courtesy of some John Golden mastering. Using a variety of synths, autoharp, melodic & even toy piano, Prezzano has created a deep & rich world that will appeal to fans of Enos Obscure label releases (Eno, Gavin Bryars, Harold Budd etc), Laraaji & some hints of STARS OF THE LIDs time-stretched masterpieces. A fantastic letterpress sleeve by Reckless own Risa Tolentino makes this limited LP even more enticing. RECOMMENDED!!", playtime: 45, label: "Love All Day", price: 20, supplier_id: 2},
#   {artist_name: "Manuel Gottsching", record_title: "E2-E4", genre: "Electronic", description: "This rare album is available next week as a reissue. Limited release in stock. Get it while you can!", playtime: 60, label: "MG Art (Reissue)", price: 30, supplier_id: 5},
#   {artist_name: "Charles Bradley", record_title: "Changes", genre: "Super Funky Sweet Soul", description: " Anticipated 2016 album from CHARLES BRADLEY (backed by the untouchable MENAHAN STREET BAND) is all of the funky, JAMES BROWN-inspired soul you need, & includes his amazing cover of BLACK SABBATH's \"Changes.\" This could have been released in 1965 if we didn't know any better. HIGHLY RECOMMENDED! *** LIMITED EDITION double LP comes with the instrumen- tals on the second record, a gatefold sleeve & an 8x10 photo! ***", playtime: 50, label: "Daptone", price: 27, supplier_id: 1},
#   {artist_name: "John Paul White", record_title: "Beulah", genre: "Outsider Folk", description: "First solo album from JOHN PAUL WHITE after the break-up of THE CIVIL WARS!", playtime: 50, label: "Single Lock", price: 17, supplier_id: 3},
#   {artist_name: "Explosions In The Sky & David Wingo", record_title: "Manglehorn", genre: "Soundtracks", description: "EXPLOSIONS IN THE SKY teamed up with David Wingo of OLA PODRIDA a few years back for the soundtrack to the David Gordon Green film \"Prince Avalanche\" & now they return with a score to another Green movie \"Manglehorn.\" There are moments like E.I.T.S. with more subdued, ambient moments mixed in.", playtime: 101, label: "Temporary Residence", price: 19, supplier_id: 2},
#   {artist_name: "John Carpenter", record_title: "Lost Themes II", genre: "Sountracks, Electronic, Ghost Music", description: "Haunted and sweet.", playtime: 101, label: "Sacred Bones", price: 20, supplier_id: 1}
# ])

Image.create([{img_url: "https://f4.bcbits.com/img/a1950601767_10.jpg", vinyl_id: 1}, {img_url: "https://f4.bcbits.com/img/a2459744213_16.jpg", vinyl_id: 2}, {img_url: "https://d1wtzzt4oxg683.cloudfront.net/images/covers/large/59/157059.jpg", vinyl_id: 3}, {img_url: "http://static.webshopapp.com/shops/029233/files/047325396/600x600x2/manuel-gottsching-e2-e4-ltd-anniversary-edition.jpg", vinyl_id: 4}, {img_url: "https://f4.bcbits.com/img/a0846266024_10.jpg", vinyl_id: 5}, {img_url: "http://dittytv.com/wp-content/uploads/2016/08/new-104-1.jpg", vinyl_id: 6}, {img_url: "http://cdn4.pitchfork.com/news/51618/cf5883f0.jpg", vinyl_id: 7}, {img_url: "http://cdn3.pitchfork.com/albums/23019/34d0283e.jpg", vinyl_id: 8}])
