Vinyl.create!([
  {artist_name: "Ryley Walker", record_title: "Golden Sings That Have Been Sung", genre: "Improv/Jazz Indie Folk", description: "Chicago's Ryley Walker continues his journey with the fantastic \"Golden Sings That Have Been Sung.\" Walker leads some of the finest players in the improv/ jazz scene with his effortless sounding guitar playing & almost-spoken, stream of consciousness singing style. This limited expanded edition features a 41 minute version of the song \"Sullen Mind\" recorded live for SiriusXM.", playtime: 48, label: "Dead Oceans", price: 19},
  {artist_name: "Celestino", record_title: "Protector's Tea", genre: "Zen Tea Ambient", description: "Featuring beautifully mastered sound by Jae-Soo Yi of Riverman Music in Seoul, in an edition of 300 copies housed in a sturdy, archival old-style LP jacket.", playtime: 30, label: "Love All Day", price: 19},
  {artist_name: "Sabbatical", record_title: "Sundown", genre: "Ambient", description: "Sundown is an album 6 years in the making by the Chicago ambient/drone artist Pete Prezzano aka SABBATICAL. These beautiful drone pieces are well recorded & the tones are warmly represented on vinyl courtesy of some John Golden mastering. Using a variety of synths, autoharp, melodic & even toy piano, Prezzano has created a deep & rich world that will appeal to fans of Enos Obscure label releases (Eno, Gavin Bryars, Harold Budd etc), Laraaji & some hints of STARS OF THE LIDs time-stretched masterpieces. A fantastic letterpress sleeve by Reckless own Risa Tolentino makes this limited LP even more enticing. RECOMMENDED!!", playtime: 45, label: "Love All Day", price: 20},
  {artist_name: "Manuel Gottsching", record_title: "E2-E4", genre: "Electronic", description: "This rare album is available next week as a reissue. Limited release in stock. Get it while you can!", playtime: 60, label: "MG Art (Reissue)", price: 30},
  {artist_name: "Charles Bradley", record_title: "Changes", genre: "Super Funky Sweet Soul", description: " Anticipated 2016 album from CHARLES BRADLEY (backed by the untouchable MENAHAN STREET BAND) is all of the funky, JAMES BROWN-inspired soul you need, & includes his amazing cover of BLACK SABBATH's \"Changes.\" This could have been released in 1965 if we didn't know any better. HIGHLY RECOMMENDED! *** LIMITED EDITION double LP comes with the instrumen- tals on the second record, a gatefold sleeve & an 8x10 photo! ***", playtime: 50, label: "Daptone", price: 27},
  {artist_name: "John Paul White", record_title: "Beulah", genre: "Outsider Folk", description: "First solo album from JOHN PAUL WHITE after the break-up of THE CIVIL WARS!", playtime: 50, label: "Single Lock", price: 17},
  {artist_name: "Explosions In The Sky & David Wingo", record_title: "Manglehorn", genre: "Soundtracks", description: "EXPLOSIONS IN THE SKY teamed up with David Wingo of OLA PODRIDA a few years back for the soundtrack to the David Gordon Green film \"Prince Avalanche\" & now they return with a score to another Green movie \"Manglehorn.\" There are moments like E.I.T.S. with more subdued, ambient moments mixed in.", playtime: 101, label: "Temporary Residence", price: 19},
  {artist_name: "John Carpenter", record_title: "Lost Themes II", genre: "Sountracks, Electronic, Ghost Music", description: "Haunted and sweet.", playtime: 101, label: "Sacred Bones", price: 20}
])
